### PR TITLE
feat: add animated terminal

### PR DESCRIPTION
**Pull request by Commandtechno**
cubxity said i could do this for hacktoberfest
hope i didnt mess too much stuff up
i couldnt get my prettier config right so if somebody could format it to this project's strandards that would be helpful

anyways heres how it looks

gif of the animated terminal

### CODE REVIEW

**Comment by Cubxity** [comment]
Think you should run `pnpm lint`. Also, could you update 1.18.2 part to 1.19.2? Perhaps pull the latest paper version in getStaticProps too

**Comment by Commandtechno** [comment]
done

**Comment by MiniDigger** [comment]
https://site-git-fork-commandtechno-main-papermc.vercel.app/
looks great

**Comment by Cubxity** [comment]
image
Looks great so far!

Could you please perform 2 small changes?
1. round the corners on top
2. make the `:` white

**Comment by Commandtechno** [comment]
done!

**Review by Cubxity — APPROVED** [review]

**Comment by Cubxity** [comment]
Thank you for your contribution!

**Comment by Commandtechno** [comment]
hacktoberfest!!! 🎉

**Pull request merged**
